### ISSUE TITLE
Problem after purchase

### ISSUE THREAD

**Issue by artemsvit** [Sanster/iopaint-docs#1]
Hello. I buy 1 click installer but not see emails, only recipt in inbox, and I don't see win_config.bat and a win_start.bat in archive. Help me. Email: artsvit@i.ua

**Comment by artemsvit** [comment]
I already receive all archive (174 MB). But I don't see any 1-click files. Help me understand.

**Comment by Sanster** [comment]
You need to unzip the `IOPaint-v1.zip` file first, then you will be able to see the `win_config.bat` and `win_start.bat` files.
<img width="143" alt="image" src="https://github.com/Sanster/iopaint-docs/assets/3998421/56867d30-a60d-41a2-bb6e-f39f9e406ffa">

**Comment by artemsvit** [comment]
I don't have this files =(( only installer folder.

**Comment by artemsvit** [comment]
UPD: I re-download purchase again and unzip it and now I see this two file. Thank you.
