### ISSUE TITLE
Feedback for “Q&A”

### ISSUE THREAD

**Issue by DutchDree** [Sanster/iopaint-docs#26]
Good afternoon,

I tried to install IOpaint with the installer, but getting the following error when trying to run win_config, even after turning of the virus scanner and firewall:

_Collecting ffmpy
Downloading ffmpy-0.3.2.tar.gz (5.5 kB)
ERROR: Error [WinError225] Operation did not complete successfully because the file contains a virus or potentially unwanted software while executing command python setup.py egg_info
Preparing metadata (setup.py) … error
ERROR: Could not install packages due to an OSError: [WinError225] Operation did not complete successfully because the file contains a virus or potentially unwanted software while executing command python setup.py egg_info.

‘iopaint’ is not recognized as an internal or external command,
Operable program or batch file.
‘iopatin’ is not recognized as an internal or external command,
Operable program or batch file.
Press any key to continue .   .   ._

Could you please advise a solution?

**Comment by Sanster** [comment]
Hi, thank you for supporting my open source project, maybe this is related to Windows Defender. I found a related solution here:

https://www.reddit.com/r/learnpython/comments/q4adla/comment/hfxbn09/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

If the problem still cannot be solved, I don't have any ideas either. Please send an email to my email address cwq1913@gmail.com, and I will give you a refund immediately.

**Comment by DutchDree** [comment]
Good morning,

Thanks for the reply, it looked like I had 2 anti-virus scanners installed and running, after turning them off temporarily it installed correctly and is now working flawlessly.
