### ISSUE TITLE
After just purchasing and installing, it has been stuck like this and nothing is displayed.

### ISSUE THREAD

**Issue by lhj5426** [Sanster/iopaint-docs#3]
![image](https://github.com/Sanster/iopaint-docs/assets/30548000/90386411-ab88-49d1-83e8-caa327fb8ac4)
![image](https://github.com/Sanster/iopaint-docs/assets/30548000/5a3fc4be-178d-4ca3-b81e-74a5009b8805)

![image](https://github.com/Sanster/iopaint-docs/assets/30548000/5259bb2a-06c0-46dd-855c-b03b3bab3b58)

After just purchasing and installing, it has been stuck like this and nothing is displayed.
The installation path is C:\DIY\IOPaint-v1.

Can you please help me? I'm encountering some issues. Previously, when my computer was not reinstalled, I used lama-cleaner without any problems. Today, my computer crashed and I had to change the system. After reinstalling, I found that the installation commands have changed. I couldn't find any tutorials online, so I had to purchase it. Now I'm facing this situation. Can you help me? Thank you.

**Comment by Sanster** [comment]
It appears that gradio hangs when starting up, I haven't found out why yet, the logs show that the dependencies are installed correctly. Could you try to see if `win_start.bat` works with the following configuration file? The `installer_config.json` file needs to be placed in the same directory as `win_start.bat`.

[installer_config.json](https://github.com/Sanster/iopaint-docs/files/14203328/installer_config.json)

**Comment by lhj5426** [comment]
> > After reinstalling, I found that the installation commands have changed.
> 
> `lama-cleaner` functionality hasn't changed at all. What do you mean by "installation commands"? Are you referring to the old `win_config.bat` and `win_start.bat` files? You can find the old files here: https://github.com/Sanster/IOPaint/tree/1.2.0/scripts/user_scripts.

I have already sent you an email.

Regarding the older version I mentioned, I previously followed a video tutorial from the internet for installation. However, due to my computer crash, the commands on GitHub are now different from the ones in the video tutorial. As a result, I am unable to install it myself. But I really want to use this tool to remove text from comics. That's why I purchased the $5 one-click installation version, which led to this post because I am unable to launch the new version.

So, I would like to request an older version of the one-click installation package from you.

**Comment by lhj5426** [comment]
> > After reinstalling, I found that the installation commands have changed.
> 
> `lama-cleaner` functionality hasn't changed at all. What do you mean by "installation commands"? Are you referring to the old `win_config.bat` and `win_start.bat` files? You can find the old files here: https://github.com/Sanster/IOPaint/tree/1.2.0/scripts/user_scripts.

![image](https://github.com/Sanster/iopaint-docs/assets/30548000/72f4f7b0-c3f5-4038-9c61-ef55eac03a16)
After using the version 3.1 that you sent me via email, I am now stuck at this point.

**Comment by Sanster** [comment]
It's still the issue of Gradio hanging. Please download this configuration file and try `win_start.bat` again.

[installer_config.json](https://github.com/Sanster/iopaint-docs/files/14208396/installer_config.json)

**Comment by lhj5426** [comment]
> It's still the issue of Gradio hanging. Please_ download _this configuration file and try `win_start.bat` again.
> 
> [installer_config.json](https://github.com/Sanster/iopaint-docs/files/14208396/installer_config.json)

Thank you. I will go ahead and run it now.

**Comment by lhj5426** [comment]
> It's still the issue of Gradio hanging. Please_ download _this configuration file and try `win_start.bat` again.
> 
> [installer_config.json](https://github.com/Sanster/iopaint-docs/files/14208396/installer_config.json)

![image](https://github.com/Sanster/iopaint-docs/assets/30548000/bb8d6997-2a32-481d-a5ee-3dbe122e783f)
Although I don't know the reason, it works this time. Thank you for your help. I want to use a separate GUI. To do that, modify "gui": false.

I have been working on it since 12 PM and it's now 8 PM. The system crashed once and I almost lost it. Anyway, thank you very much for your help.
