### ISSUE TITLE
CUDA报错，Python一直安装不上

### ISSUE THREAD

**Issue by wxdlovezyd** [Sanster/iopaint-docs#36]
您好，一键启动脚本启动最后报错，查询相关资料应该是CUDE和pytorch版本不一致导致
     首先有一个疑问，我在cmd里执行python --version输出的结果是python版本是3.8，对应的CUDE版本是11.4，但是为什么在启动脚本里我看到python的版本有又是3.10.6？
     我用PIP方式安装，用的这句话：pip install torch==1.10.0+cpu torchvision==0.11.1+cpu torchaudio==0.10.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
报错：ERROR: Could not find a version that satisfies the requirement torch==1.10.0+cpu (from versions: none)
ERROR: No matching distribution found for torch==1.10.0+cpu
    随后我手动安装，在网站下载torch-1.10.0-cp38-cp38-win_amd64.whl这个文件，手动安装，
报错：ERROR: torch-1.10.0-cp38-cp38-win_amd64.whl is not a supported wheel on this platform
    所以我不知道我卡到哪里了，也不知道该如何去排查了，麻烦您帮我看看谢谢
![微信截图_20240910162036](https://github.com/user-attachments/assets/fbc4ce57-4373-4a42-83f6-c6cbdf2e1770)
![微信截图_20240910162108](https://github.com/user-attachments/assets/6a316f4e-8ab0-431d-83cf-bb64fc37e268)
![微信截图_20240910162228](https://github.com/user-attachments/assets/77104fb0-0516-4744-b6f0-43d3295ecfc1)

**Comment by zhaojigang** [comment]
我用 python3.12 装成功了 还比较顺利

**Comment by Sanster** [comment]
之前已经通过邮件回复了，先关闭
