### ISSUE TITLE
What's next? Please, explain how to install

### ISSUE THREAD

**Issue by Yp-pro** [Sanster/iopaint-docs#4]
Hello, Sanster! Thanks for you app, it looks cool. 

But I've got a problem. I'm not a dev, so could you explain how to use it? 

OK, the Erase works out of the box, but how to install another tools? What's that "--model Sanster/AnyText"? What should I do with that? Every part in your cool manual starts with this mistery. 

There is an amazing tool Replace Object (here: Generate Darth Vader on a beach using [PowerPaint]https://www.iopaint.com/). But I can't find the text prompt form in my IOpaint, only "Upload an image":

![image](https://github.com/Sanster/iopaint-docs/assets/156006482/321afa61-df3e-4048-929b-d2e8f04840c7)

Please, describe it for non-devs. 

Best wishes, Yar

**Comment by Sanster** [comment]
Indeed, there's a lot of work to do on the document...The erase model does not support text prompts, so I have hidden some unnecessary interfaces when using the erase model. You can switch models using the following methods:

On the configuration page, you can enter the model name in "Current Model", including the models mentioned in [models](https://www.iopaint.com/models), for example,  `Sanster/AnyText` or `Sanster/PowerPaint-V1-stable-diffusion-inpainting`

You can also choose from "Recommended Models" or "Downloaded Models", once selected, it will automatically populate in the "Current Model". Then click `Save Configurations` to save the settings.

Model will be automatically downloaded the first time it is used.

https://github.com/Sanster/iopaint-docs/assets/3998421/877cfd8b-0dc3-4374-a18c-c70030745d88

保存下来的配置是一个 json 文件，你也可以用文本编辑器直接打开它，修改其中的 `model` 配置，例如把这里的 `"model": "Sanster/PowerPaint-V1-stable-diffusion-inpainting"` 改成 `"model": "Sanster/AnyText"`

```json
{
    "host": "127.0.0.1",
    "port": 8080,
    "model": "Sanster/PowerPaint-V1-stable-diffusion-inpainting",
    "no_half": false,
    "low_mem": false,
    "cpu_offload": false,
    "disable_nsfw_checker": false,
    "local_files_only": false,
    "cpu_textencoder": false,
    "device": "cuda",
    "input": null,
    "output_dir": null,
    "quality": 95,
    "enable_interactive_seg": false,
    "interactive_seg_model": "vit_b",
    "interactive_seg_device": "cpu",
    "enable_remove_bg": false,
    "enable_anime_seg": false,
    "enable_realesrgan": false,
    "realesrgan_device": "cpu",
    "realesrgan_model": "realesr-general-x4v3",
    "enable_gfpgan": false,
    "gfpgan_device": "cpu",
    "enable_restoreformer": false,
    "restoreformer_device": "cpu"
}
```
