### ISSUE TITLE
config以及start运行会报错

### ISSUE THREAD

**Issue by yeshen001** [Sanster/iopaint-docs#47]
![1](https://github.com/user-attachments/assets/4a458297-a4e1-47e7-914d-254efd42f2f8)
![2](https://github.com/user-attachments/assets/19a745c0-b1dc-4e7e-8b11-a88835856c21)

运行config.bat和start.bat时会报错，看起来是缺失文件，

config运行的报错指向的c盘.cache里的json文件，我看了下，是存在的，但大小为0kb，是个空文件

start运行时报错的缺失文件，并不存在，

请教下，是否是哪里操作不当引起的，如果实在找不出原因，那么这个两个缺失的文件是否可以手动补上

**Comment by Sanster** [comment]
你好，第一个问题是由于文件是空文件，这个问题已经在 `1.5.2` 里面修复了，忽略了 cache 里面错误的 json 文件。你也可以试下手动把那个 model_index.json 删除，然后在执行 win_config.bat

成功运行 win_config 并保存配置后(installer_config.json)，win_start 就可以执行了
