### ISSUE TITLE
Unable to enter spaces between words for prompt when inpainting

### ISSUE THREAD

**Issue by NamNguyenUTSA** [Sanster/iopaint-docs#7]
![Screenshot 2024-02-26 015159](https://github.com/Sanster/iopaint-docs/assets/47985283/75b813a9-a8a5-45ef-aab7-8348d055ed11)

Hello! I just purchased the installer today, and am unable to add any spaces between words in the prompt bar, but only after loading an image (in the screenshot, there are underscores between each word). This happens when inpainting with with the anything v4.0 model. Any ideas on what's causing this?

**Comment by Sanster** [comment]
This is a bug, a new version will be released in the next couple of days to fix it.

**Comment by Sanster** [comment]
fixed in 1.2.1
